packages:
  - '**/*'
  - '!collaboration/tiptap-cloud'

ignoredBuiltDependencies:
  - '@microsoft/teamsapp-cli'
  - core-js
  - keytar
  - leveldown
  - sharp
  - vue-demi

onlyBuiltDependencies:
  - esbuild

overrides:
  superdoc: file:../packages/superdoc/superdoc.tgz
